services:
  - type: web
    name: influencons
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: influencons-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: admin@influencons.com
      - key: ADMIN_PASSWORD
        value: changeme123

databases:
  - name: influencons-db
    databaseName: influencons
    user: influencons
